name: NASA Project CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    env:
      MONGO_URL: mongodb://localhost/nasa
    strategy:
      matrix:
        mongodb-version: ['4.4']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use NodeJS version 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: npm install
      - run: npm run ubuntu-build --prefix client
      - run: npm run test --prefix server
